# Generated by Django 3.0.3 on 2020-02-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200226_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('FavNo', models.IntegerField()),
            ],
            options={
                'db_table': 'Friends',
            },
        ),
    ]
